### ISSUE TITLE
Advanced options are not showing

### ISSUE THREAD

**Issue by bcbooker** [phroph/magicsim#1]
I currently am running Windows 7 SP1. Whenever I open the advanced tab for magicsim, nothing shows up. Cannot resize the window either.

![error](https://cloud.githubusercontent.com/assets/26436170/23951486/e0a61664-09d9-11e7-8e05-1226dc4b9e24.png)

**Comment by phroph** [comment]
What resolution / DPI are you running at?

**Comment by bcbooker** [comment]
Resolution is 1920x1080. Not sure what my DPI is

**Comment by phroph** [comment]
Diagonal size of the screen should be fine I think.

**Comment by phroph** [comment]
Though I'm pretty sure the problem here is just for some reason the window isn't wide enough to support the panel (and you can see the advanced panel trying to poke out in the bottom left corner). There should be a few easy ways to fix it, though it's a little weird to me (and I've seen this in my testing) that the window doesn't always have the right precise scale always and seems to act within certain margins of quirkyness.

I'll post some mitigations in a few minutes, just want to test them out. This will be fixed in the next release definitely.

**Comment by phroph** [comment]
Easiest fix is likely going to package.nw/web/index.html and going to line 186,              `require('nw.gui').Window.get().width = 655;`, and changing it to                 `require('nw.gui').Window.get().width = 700;`

Let me know if that works.

**Comment by bcbooker** [comment]
Thank worked, thanks !
