### ISSUE TITLE
Closes on it's own

### ISSUE THREAD

**Issue by tvandell** [phroph/magicsim#13]
I start the application and get the inital options screen (Quick Sim, Armory etc). Then when on the next screen as soon as I click anywhere in the screen the app closes. Tried it several times and closes on me everytime.

**Comment by drnymfromhyjal** [comment]
same thing is happening to me.  Ran it as admin too and it still crashed.  crashing for me before I can choose the realm.

**Comment by drnymfromhyjal** [comment]
Still haven't found a solution.  Hopefully Proph will see this soon and give us some feedback.  He's usually really helpful.  Maybe just too busy the last few days to get back to us.

I'm really wanting to get it fixed because all my PAWN strings are wrong and I need to help to get them fixed for the new raid.  I was gone doing my Naturopath testing and missed the first two weeks of the raid and now I am trying to get caught up

**Comment by drnymfromhyjal** [comment]
Looks like they moved the newest version to 
https://github.com/phroph/magicsim/releases/tag/2.3.0.0

I will try to download the new version.

**Comment by drnymfromhyjal** [comment]
Nope, the new version doing the same thing.  Please help Phroph

**Comment by phroph** [comment]
(going through old bugs)
I think this was related to an issue with some outdated code. Might've been related to the project being on hiatus for a little bit.

However, I'm trying to rewrite the engine to better support these cases and be a little more resilient

Sorry it's been a slow crawl through BFA with some of these issues. Hopefully going forward we won't have as many issues like this.

If, after the rebooted version (that I'm still working on, I'll make a big thing about it when its available), there are still similar issues. Please feel free to re-open and pester me. Also please feel free to pester me on discord (semicolondash#3014) if im slow to respond here (I dont get email notifications for Github it seems like and need to set that up better going forward so i can capture bugs as they are reported).
