### ISSUE TITLE
Attached simc appears to consistently crash magicsim during the second sim.

### ISSUE THREAD

**Issue by jshantz** [phroph/magicsim#3]
Version: 2.0.1.1

Steps:

1. Run magicsim.exe. 
2. Click 'From /simc'.
3. Paste the simc data below.
4. Click Continue.
5. Click Add.
6. Click Simulate.

Behavior: Crashes during simulation 2/10. Observed three times.

Let me know if I can provide more info.

----
```
# SimC Addon 1.9.1

hunter="Ape"
level=110
race=troll
region=us
server=mugthol
role=attack
professions=alchemy=793/herbalism=754
talents=3321231
spec=survival
artifact=34:0:0:0:0:1370:1:1338:1:1638:1:1083:1:1082:1:1081:1:1080:1:1068:1:1070:4:1071:4:1072:4:1079:1:1078:4:1077:4:1525:4:1526:1:1527:1:1528:24:1076:4:1075:4:1084:1:1074:4:1073:4
crucible=1739:1774:1073/1739:1778:1073/1739:1779:1073

head=,id=137064,bonus_id=1811/3630
neck=,id=151965,enchant_id=5437,bonus_id=3611/1502/3337
shoulder=,id=152371,enchant_id=5929,bonus_id=3614/1472/3528
back=,id=151937,enchant_id=5435,bonus_id=3611/1487/3528
chest=,id=151995,bonus_id=3611/1492/3336
wrist=,id=137101,bonus_id=3529/1811/3630
hands=,id=152132,bonus_id=3611/1492/3336
waist=,id=152683,gem_id=151583,bonus_id=3611/1808/1502/3337
legs=,id=152134,bonus_id=3611/1487/3528
feet=,id=134166,bonus_id=3536/1622/3337
finger1=,id=152284,enchant_id=5428,gem_id=151583,bonus_id=3613/1808/1487/3337
finger2=,id=149667,enchant_id=5428,gem_id=151583,bonus_id=3573/1808/1572/3528
trinket1=,id=151964,bonus_id=3613/1467/3336
trinket2=,id=141482,bonus_id=3466/1487/3337
main_hand=,id=128808,gem_id=152058/137408/151296,bonus_id=728,relic_id=3611:1487:3528/3536:1592:3528/3573:1562:3528

### Gear from Bags
#
# Helm of the Vigilant Eye (930)
# head=,id=152369,bonus_id=3614/1472/3528
#
# Collar of Null-Flame (945)
# neck=,id=151973,bonus_id=3611/1487/3528
#
# Prydaz, Xavaric's Magnum Opus (1000)
# neck=,id=132444,enchant_id=5437,gem_id=151583,bonus_id=1811/3630
#
# Serpentstalker Drape (920)
# back=,id=152131,bonus_id=3613/1462/3336
#
# Butcher's Bone Apron (1000)
# chest=,id=144361,bonus_id=3459/3630
#
# Fleet Commander's Hauberk (945)
# chest=,id=151994,bonus_id=3611/1487/3528
#
# Serpentstalker Tunic (945)
# chest=,id=152130,bonus_id=3611/1487/3528
#
# Nether Mindsnappers (905)
# hands=,id=134467,bonus_id=3418/1557/3337
#
# Waistguard of Devilish Deeds (930)
# waist=,id=152372,bonus_id=3614/1472/3528
#
# Ring of Braided Stems (895)
# finger1=,id=140896,enchant_id=5428,bonus_id=3514/1492/3337
#
# Kil'jaeden's Burning Wish (1000)
# trinket1=,id=144259,bonus_id=3459/3630
#
# Eye of Command (915)
# trinket1=,id=142167,bonus_id=3573/1527/3336
#
```

**Comment by phroph** [comment]
This is a sortof known issue with SimC. I'm gonna leave this open and for triage because it falls under an umbrella of "bad APLs" which is a loose term. But basically the problem here is some sims use invulnerabilities to prevent a boss from taking damage during transitions, and some APLs internal code cannot handle this scenario and crash. I have a task on me to try to remove these raid events and find alternatives to them without using invulnerabilities.

However, actually fixing the root of the problem involves the APL maintainers cleaning up their code and making it handle these edge cases (which is out of my expertise, though I have considered it).

The mitigation is to use classic composite. The accuracy is pretty comparable (especially for specs which do not support advanced raid events) and it has a slightly faster runtime. I'll try to address this in the next update.

Some other specs that face this issue (known):
Arcane Mages
Fury Warriors

Thanks for the report (it really helps knowing what specs are impacted by this aswell. May need to report it to the respective APL maintainers. Then again they may not be supported or may not care to support this case, etc.)

**Comment by jshantz** [comment]
Thanks for the thorough rundown of what's going on. I'll give Classic Composite a go and see if I can track down the Survival APL maintainer.

**Comment by phroph** [comment]
@jshantz I'm closing this now because the new version of Antorus Composite should now work on Survival hunter. If the problem persists after updating just reopen and i can dig deeper. But this should fix the bulk of possible problems.
